server:
  port: 9000
spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#/order-service/api/v1/order/save?product_id=1&user_id=1
zuul:
  routes:
    order-service: /apigateway/order/**
    product-service: /apigateway/product/**
    #user-service: /apigateway/**
  ignored-patterns: /*-service/**
  sensitive-headers:
